#!/bin/bash

echo -e "\033[93mDigite o \033[96mDominio/Url \033[93mque deseja analisar:\033[0m"
read url

# Verifica se a URL começa com "https://"
if [[ "${url}" != "https://"* ]]; then
# Se a URL não começa com "https://", adiciona "https://" no início
  url="https://${url}"
fi
echo -e "\033[93mAtualmente analisando o link: \033[96m${url}\033[0m"

#Funções do código
menu(){
    echo -e "1-\033[92mUsar o ParamSpider\033[0m"
    echo -e "2-\033[95mUsar Nuclei\033[0m"
    echo -e "3-\033[94mSubdominios ativos\033[0m"
    echo -e "9-\033[93mSair\033[0m"
}

parametro(){
    echo -e "executando paramspider em \033[92m$url\033[0m"
    paramspider  -d  "$url"
}

nuclei(){
    echo -e "\033[93m Quais templates quer usar?\033[92m"
    echo -e "1-todos"
    echo -e "2-exposures"
    echo -e "3-cves"
    echo -e "4-exposed panels"
    echo -e "5-fuzzing"
    echo -e "6-vulnerabilities\033[0m"

    read template
# Path dos templates(altere se precisar)
    case $template in

        1)
            ~/go/bin/nuclei -u $url -t ~/nuclei-templates
            ;;
        2)
            ~/go/bin/nuclei -u $url -t ~/nuclei-templates/exposures
            ;;
        3)
            ~/go/bin/nuclei -u $url -t ~/nuclei-templates/cves
            ;;
        4)
            ~/go/bin/nuclei -u $url -t ~/nuclei-templates/exposed-panels
            ;;
        5)
            ~/go/bin/nuclei -u $url -t ~/nuclei-templates/fuzzing
            ;;
        6)
            ~/go/bin/nuclei -u $url -t ~/nuclei-templates/vulnerabilities
            ;;

        *)
            echo -e "\033[93mOpção invalida \033[96m(⁠╯⁠°⁠□⁠°⁠）⁠╯⁠︵⁠ ⁠┻⁠━⁠┻\033[0m"
            return
            ;;
    esac
}

#Devido a problemas ao iniciar as ferramentas pelo path ~/go/bin as ferramentas em golang são copiadas para /etc/bin ao usar os scripts de instalação.
subd(){
    subfinder -d "${url##https://}" | httpx -sc -title
}

#Loop do código
while true; do

    menu

    read opcao

    case $opcao in
            1)
                parametro
                ;;
            2)
                nuclei
                ;;
            3)
                subd
                ;;
            9)
                echo -e "\033[93mSaindo...\033[0m"
                exit 0
                ;;
            *)
                echo -e "\033[93mOpção invalida \033[96m(⁠╯⁠°⁠□⁠°⁠）⁠╯⁠︵⁠ ⁠┻⁠━⁠┻\033[0m"
                ;;
    esac
done
