#!/bin/bash

if [ "$(uname)" != "Linux" ]; then
    printf "\033[1;32mVocê não está usando um sistema GNU/Linux ou similar\033[0m\n"
    exit 1
fi

clear

printf "\033[1;36m Vamos começar atualizando o \033[1;92mLinux...\033[0m\n"
sleep 3

cd ~

sudo apt update -y && sudo apt full-upgrade -y

clear

printf "\033[1;36m Instalando as duas linguagens necessárias \033[1;92mPython e Golang...\033[0m\n"
sleep 3

# Instalando o Python
sudo apt install python -y

# Instalando o Go
sudo apt install golang -y

# Instalando o curl e o wget
sudo apt install curl wget -y

clear

printf "\033[1;36m Instalando ferramentas em \033[1;32mGolang...\033[0m\n"
sleep 3

declare -A ferramentas=(
    ["kxss"]="github.com/Emoe/kxss@latest"
    ["subfinder"]="github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest"
    ["httpx"]="github.com/projectdiscovery/httpx/cmd/httpx@latest"
    ["gau"]="github.com/lc/gau/v2/cmd/gau@latest"
    ["anew"]="github.com/tomnomnom/anew@latest"
    ["ffuf"]="github.com/ffuf/ffuf@latest"
    ["nuclei"]="github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest"
)

for ferramenta in "${!ferramentas[@]}"; do
    printf "\033[92mInstalando \033[96m%s\033[0m\n" "$ferramenta"
    sleep 3
    go install -v "${ferramentas[$ferramenta]}"
done

~/go/bin/nuclei -update-templates

sleep 3

clear

printf "\033[1;36m Baixando repositórios de ferramentas de \033[92mPYTHON \033[36me o \033[94mSecList...\033[0m\n"
sleep 3

declare -A repos=(
    ["ParamSpider"]="https://github.com/devanshbatham/ParamSpider"
    ["Cam-Hackers"]="https://github.com/AngelSecurityTeam/Cam-Hackers"
    ["EyeSeeYou"]="https://github.com/BraydenP07/EyeSeeYou"
    ["sherlock"]="https://github.com/sherlock-project/sherlock"
    ["git-dumper"]="https://github.com/arthaud/git-dumper"
    ["zphisher"]="https://github.com/htr-tech/zphisher"
    ["SecLists"]="https://github.com/danielmiessler/SecLists"
    ["sqlmap"]="https://github.com/sqlmapproject/sqlmap"
)

for repo in "${!repos[@]}"; do
    if [ -d "$repo" ]; then
        printf "\033[92mAtualizando o repositório \033[96m%s\033[0m\n" "$repo"
        cd "$repo" || exit
        git reset --hard
        git pull
        if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
            if [ "$repo" == "ParamSpider" ]; then
                pip install -r .
            else
                printf "\033[91mO arquivo requirements.txt não existe neste repositório\033[0m\n"
            fi
        else
            printf "\033[91mO arquivo requirements.txt não existe neste repositório\033[0m\n"
        fi
        cd ..
    else
        printf "Clonando %s...\n" "$repo"
        git clone --recurse-submodules "${repos[$repo]}"
        cd "$repo" || exit
        if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
        if [ "$repo" == "ParamSpider" ]; then
            pip install -r .            
        fi
        else
            printf "\033[91mO arquivo requirements.txt não existe neste repositório\033[0m\n"
        cd ..
    fi
done

clear

printf "\033[1;92mInstalação concluída\033[0m\n"
sleep 3
clear

sudo cp ~/go/bin/* /usr/bin

printf "\033[93mAviso: \033[92mAs ferramentas em Golang foram copiadas para /usr/bin para facilitar o uso das mesmas.\n"
printf "Ao invés de digitar o caminho ~/go/bin/ferramenta você poderá agora chamar a ferramenta apenas digitando o seu nome\033[0m\n"
printf "Ex1: \033[96msubfinder -d alvo\033[0m\n"
printf "Ex2: \033[94mffuf -u alvo/FUZZ(palavra padrão para ser substituída pelas da wordlist) -w caminho da wordlist\033[0m\n"
printf "Ex3: \033[95mnuclei -u alvo -t ~/nuclei-templates/cves\033[0m\n"
exit 0
