#!/bin/bash

printf "\033[93mEsse script foi feito com o propósito de ser usado no Kali para o userland\033[0m\n"

sleep 2

if [ "$(uname)" != "Linux" ]; then
    printf "\033[1;32mVocê não está usando um sistema GNU/Linux ou similar\033[0m\n"
    exit 1
fi

clear

printf "\033[1;36m Vamos começar atualizando o \033[1;92mLinux...\033[0m\n"
sleep 3

cd ~

sudo apt update -y 

clear

printf "\033[36mInstalando linguagens de programação e ferramentas necessárias....\033[0m\n"
sleep 3

# Instando pacotes
sudo apt install python3 -y
sudo apt install pypy3-venv -y
sudo apt install golang -y
sudo apt install curl -y
sudo apt install wget -y
clear

printf "\033[36m Instalando ferramentas em Golang...\033[0m\n"
sleep 3

declare -A ferramentas=(
    ["kxss"]="github.com/Emoe/kxss@latest"
    ["subfinder"]="github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest"
    ["httpx"]="github.com/projectdiscovery/httpx/cmd/httpx@latest"
    ["gau"]="github.com/lc/gau/v2/cmd/gau@latest"
    ["anew"]="github.com/tomnomnom/anew@latest"
    ["ffuf"]="github.com/ffuf/ffuf@latest"
    ["getJS"]="github.com/003random/getJS@latest"
)

for ferramenta in "${!ferramentas[@]}"; do
    printf "\033[92mInstalando \033[96m%s...\033[0m\n" "${ferramenta}"
    sleep 1
    go install -v "${ferramentas[$ferramenta]}"
done

clear

printf "\033[36mBaixando repositórios de outras ferramentas necessárias para o script \033[92mtestadordeurl\033[0m...\n"
printf "\033[91mAlgumas ferramentas possuem instalações diferentes. Verifique como instalar as ferramentas pesquisando elas em \033[92mhttps://github.com\033[0m\n"
printf "\033[92mBaixando pipx\033[0m\n"

# O kali linux deixou de usar o pip e recomenda o uso do pipx, mais a frente um ambiente virtual será criado para usar o pip para instalar as ferramentas 
sudo apt install pipx -y

sleep 3

# Baixando Repositórios
declare -A links=(
    ["ParamSpider"]="https://github.com/devanshbatham/ParamSpider"
    ["Cam-Hackers"]="https://github.com/AngelSecurityTeam/Cam-Hackers"
    ["EyeSeeYou"]="https://github.com/BraydenP07/EyeSeeYou"
    ["sherlock"]="https://github.com/sherlock-project/sherlock"
    ["git-dumper"]="https://github.com/arthaud/git-dumper"
    ["zphisher"]="https://github.com/htr-tech/zphisher"
    ["cam-finder"]="https://github.com/member87/cam-finder.git"
    ["sqlmap"]="https://github.com/sqlmapproject/sqlmap"
    ["https-github.com-Rajkumrdusad-Tool-X"]="https://github.com/vaibhavguru/https-github.com-Rajkumrdusad-Tool-X.git"
)

for repo in "${!links[@]}"; do
    if [ ! -d "$repo" ]; then
        # Diretório não existe, então clone-o
        printf "Clonando %s...\n" "${repo}"
        git clone "${links[$repo]}"
    else
        printf "\033[92mAtualizando o repositório \033[96m%s...\033[0m\n" "${repo}"
        git -C "$repo" reset --hard
        git -C "$repo" pull
    fi
done

# Criando o ambiente virtual
python3 -m venv venv/tools
source venv/tools/bin/activate

for repo in "${!links[@]}"; do
    REPO_PATH="./${repo}"

    if [ -f "$REPO_PATH/setup.py" ] || [ -f "$REPO_PATH/pyproject.toml" ]; then
        printf "\033[1;92mTentando instalar $repo com pip\033[0m\n"
 
        pip install "$REPO_PATH" || printf "\033[1;91mFalha ao instalar $repo com pip. Instale manualmente se necessário.\033[0m\n"
    else
        printf "\O33[1;93mRepositório $repo não é um pacote Python instalável. Instalação manual será necessária.\033[0m\n"
    fi

    cp ~/venv/tools/bin/${repo} /usr/local/bin/ 2>/dev/null || printf "\033[1;93m]Executável ${repo} não encontrado no venv/bin\033[0m\n"
done

deactivate
clear

printf "\033[1;92mInstalação concluída\033[0m\n"
sleep 3
clear

cp ~/go/bin/* /usr/local/bin

printf "\033[93mAviso: \033[92mAs ferramentas em Golang foram copiadas para ~/usr/local/bin para facilitar o uso das mesmas.\n"
printf "Ao invés de digitar o caminho ~/go/bin/ferramenta, você poderá agora chamar a ferramenta apenas digitando o seu nome\033[0m\n"
printf "Ex1: \033[96msubfinder -d alvo\033[0m\n"
printf "Ex2: \033[94mffuf -u alvo/FUZZ(palavra padrão para ser substituída pelas da wordlist) -w caminho da wordlist\033[0m\n"
printf "Ex3: \033[95mnuclei -u alvo -t ~/nuclei-templates/cves\033[0m\n"
