#!/bin/bash 

if [ "$(uname)" != "Linux" ]; then
    printf "\033[1;32mVocê não está usando o Termux (GNU/Linux)\033[0m\n"
    exit 1
fi 

clear 

printf "\033[1;36m Vamos começar atualizando o \033[1;92mTermux...\033[0m\n"
sleep 3 

cd ~ 

apt update -y && apt full-upgrade -y 

clear 

printf "\033[1;36m Instalando o Wget e Curl, e as duas linguagens necessárias \033[1;92mPython e Golang....\033[0m\n"
sleep 3 

# Instalando pacotes
apt install python -y
apt install golang -y
apt install curl -y
apt install wget -y 

clear 

printf "\033[1;36m Instalando ferramentas em \033[1;32mGolang...\033[0m\n"
sleep 3 

declare -A ferramentas=(
    ["kxss"]="github.com/Emoe/kxss@latest"
    ["subfinder"]="github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest"
    ["httpx"]="github.com/projectdiscovery/httpx/cmd/httpx@latest"
    ["gau"]="github.com/lc/gau/v2/cmd/gau@latest"
    ["anew"]="github.com/tomnomnom/anew@latest"
    ["ffuf"]="github.com/ffuf/ffuf@latest"
    ["nuclei"]="github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest"
) 

for ferramenta in "${!ferramentas[@]}"; do
    printf "\033[92mInstalando \033[96m%s...\033[0m\n" "${ferramenta}"
    sleep 1
    go install -v "${ferramentas[$ferramenta]}"
done 

~/go/bin/nuclei -update-templates 

sleep 3 

clear 

printf "\033[1;36m Baixando repositórios de ferramentas de \033[92mPYTHON\033[0m\n"
sleep 3 

# Baixando Repositórios do GitHub
declare -A links=(
    ["ParamSpider"]="https://github.com/devanshbatham/ParamSpider"
    ["Cam-Hackers"]="https://github.com/AngelSecurityTeam/Cam-Hackers"
    ["EyeSeeYou"]="https://github.com/BraydenP07/EyeSeeYou"
    ["sherlock"]="https://github.com/sherlock-project/sherlock"
    ["git-dumper"]="https://github.com/arthaud/git-dumper"
    ["zphisher"]="https://github.com/htr-tech/zphisher"
    ["cam-finder"]="https://github.com/member87/cam-finder.git"
    ["sqlmap"]="https://github.com/sqlmapproject/sqlmap"
    ["Tool-X"]="https://github.com/vaibhavguru/https-github.com-Rajkumrdusad-Tool-X.git"
)

for repo in "${!links[@]}"; do
    if [ ! -d "$repo" ]; then
        # Diretório não existe, então clone-o
        printf "Clonando %s...\n" "${repo}"
        git clone "${links[$repo]}" 

        # Verificar e instalar requirements.txt se existir
        if [ -f "${repo}/requirements.txt" ]; then
            printf "\033[92mInstalando dependências com pip para %s...\033[0m\n" "${repo}"
            pip install -r "${repo}/requirements.txt"
        fi 

        if [ "$repo" == "ParamSpider" ]; then
            # Apenas para o ParamSpider, instalação diferente.
            printf "\033[92mInstalando ParamSpider...\033[0m\n"
            pip install "$repo"
        fi 
      
        if [ "$repo" == "Tool-X" ]; then
            printf "\033[93mInstalando o %s...\033[0m\n" "${repo}"
            if [ -f "${repo}/install.aex" ]; then
                chmod +x "${repo}/install.aex"
                ./{repo}/install.aex
            fi
        fi
    else
        printf "\033[92mAtualizando o repositório \033[96m%s...\033[0m\n" "${repo}"
        git -C "$repo" reset --hard
        git -C "$repo" pull
    fi
done 

clear 

printf "\033[1;92mInstalação concluída\033[0m\n"
sleep 3
clear 

cp ~/go/bin/* ~/../usr/bin 

printf "\033[93mAviso: \033[92mAs ferramentas em Golang foram copiadas para ~/../usr/bin para facilitar o uso das mesmas.\n"
printf "Ao invés de digitar o caminho ~/go/bin/ferramenta, você poderá agora chamar a ferramenta apenas digitando o seu nome\033[0m\n"
printf "Ex1: \033[96msubfinder -d alvo\033[0m\n"
printf "Ex2: \033[94mffuf -u alvo/FUZZ(palavra padrão para ser substituída pelas da wordlist) -w caminho da wordlist\033[0m\n"
printf "Ex3: \033[95mnuclei -u alvo -t ~/nuclei-templates/cves\033[0m\n"
