#!/bin/bash

# Checa se o sistema é Linux ou não
# Se for, o processo continua. Caso contrário, a aplicação será fechada.

if [ "$(uname)" != "Linux" ]; then
    echo -e "\033[1;32mVocê não está usando um sistema GNU/Linux ou similar\033[0m"
    exit 1
fi

clear

echo -e "\033[1;36m Vamos começar atualizando o \033[1;92mTermux...\033[0m"
sleep 3

cd ~

apt update -y && apt full-upgrade -y

clear

echo -e "\033[1;36m Instalando o Wget e Curl, e as duas linguagens necessarias \033[1;92mPython e Golang....\033[0m"

sleep 3

# Instalando pacotes
apt install python golang curl wget -y

clear

echo -e "\033[1;36m Instalando ferramentas em \033[1;32mGolang...\033[0m"

sleep 3
                                                                                                    
declare -A ferramentas=(

   ["kxss"]="github.com/Emoe/kxss@latest"                                                            
   ["subfinder"]="github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest"

   ["httpx"]="github.com/projectdiscovery/httpx/cmd/httpx@latest"

   ["gau"]="github.com/lc/gau/v2/cmd/gau@latest"

   ["anew"]="github.com/tomnomnom/anew@latest"

   ["ffuf"]="github.com/ffuf/ffuf@latest"

   ["nuclei"]="github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest"
)

for ferramenta in "${!ferramentas[@]}"; do

  echo -e "\033[92mInstalando \033[96m${ferramenta}...\033[0m"
  sleep 1
  go install -v "${ferramentas[$ferramenta]}"
done

~/go/bin/nuclei -update-templates

sleep 3

clear

echo -e "\033[1;36m Baixando repositórios de ferramentas de \033[92mPYTHON \033[36me o \033[94mSecList...\033[0m"

sleep 3

#Baixando Repositorios do GitHub
declare -A repos=(

  ["ParamSpider"]="https://github.com/devanshbatham/ParamSpider"

  ["Cam-Hackers"]="https://github.com/AngelSecurityTeam/Cam-Hackers"

  ["EyeSeeYou"]="https://github.com/BraydenP07/EyeSeeYou"

  ["sherlock"]="https://github.com/sherlock-project/sherlock"

  ["git-dumper"]="https://github.com/arthaud/git-dumper"

  ["zphisher"]="https://github.com/htr-tech/zphisher"

  ["SecLists"]="https://github.com/danielmiessler/SecLists"
  ["sqlmap"]="https://github.com/sqlmapproject/sqlmap"
)

for repo in "${!repos[@]}"; do
  if [ -d "$repo" ]; then
    # Diretório já existe, então atualize-o
    echo -e "\033[92mAtualizando o repositório \033[96m${repo}...\033[0m"
    cd "$repo"
    git reset --hard
    git pull
    if [ -f "requirements.txt" ]; then
      pip install -r requirements.txt
      if [ "$repo" == "ParamSpider" ]; then
        pip install -r .
      else
        echo -e "\033[91mO arquivo requirements.txt não existe neste repositório\033[0m"
      fi
    else
      echo -e "\033[91mO arquivo requirements.txt não existe neste repositório\033[0m"
    fi
    cd ..
  else
    # Diretório não existe, então clone-o
    echo "Clonando ${repo}..."
    git clone "${repos[$repo]}"
    cd "$repo"
    if [ -f "requirements.txt" ]; then
      pip install -r requirements.txt
      if [ "$repo" == "ParamSpider" ]; then
        pip install -r .
      else
        echo -e "\033[91mO arquivo requirements.txt não existe neste repositório\033[0m"
      fi
    else
      echo -e "\033[91mO arquivo requirements.txt não existe neste repositório\033[0m"
    fi
    cd ..
  fi
done


clear

echo -e "\033[1;92mInstalação concluida\033[0m"
sleep 3
clear

cp ~/go/bin/* ~/../usr/bin

echo -e "\033[93mAviso: \033[92mAs ferramentas em Golang foram copiadas para ~/../usr/bin para facilitar o uso das mesmas."
echo -e "Ao inves de digitar o caminho ~/go/bin/ferramenta você poderá agora chamar a ferramenta apenas digitando o seu nome\033[0m"
echo -e "Ex1: \033[96msubfinder -d alvo\033[0m"
echo -e "Ex2: \033[94mffuf -u alvo/FUZZ(palavra padrão para ser substituida pelas da wordlist) -w caminho da wordlist\033[0m"
echo -e "Ex3: \033[95mnuclei -u alvo -t ~/nuclei-templates/cves\033[0m"
exit 0
